# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    consumer_message_processor:
        class: AppBundle\Service\ConsumerProcessor
        tags:
            - { name: 'enqueue.client.processor' }